name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build (PyInstaller onedir, windowed)
      run: |
        if (Test-Path assets/app.ico) {
          pyinstaller --noconfirm --onedir --windowed --name "VirtualMicRelay" --icon "assets/app.ico" app.py
        } else {
          pyinstaller --noconfirm --onedir --windowed --name "VirtualMicRelay" app.py
        }

    - name: Zip dist
      run: |
        cd dist
        powershell Compress-Archive -Path "VirtualMicRelay" -DestinationPath "VirtualMicRelay.zip"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: VirtualMicRelay-Windows
        path: dist/VirtualMicRelay.zip
